project_id = "vciqmwzgfjxtzagaxgnh"

[functions.send-daily-reminders]
verify_jwt = false

[functions.send-handbook-reminders]
verify_jwt = false

[functions.assign-assistant]
verify_jwt = false

[functions.send-birthday-reminders]
verify_jwt = false