project_id = "vciqmwzgfjxtzagaxgnh"

[functions.send-daily-reminders]
verify_jwt = false

[functions.send-handbook-reminders]
verify_jwt = false

[functions.assign-assistant]
verify_jwt = false

[functions.reassign-assistant]
verify_jwt = false

[functions.check-expired-assignments]
verify_jwt = false

[functions.send-birthday-reminders]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.send-inactivity-alerts]
verify_jwt = false